name: SP Test
on:
  push:
    branches:
      - main
jobs:
  vm_refresher:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "Hello World!"
          echo ${{secrets.TEST_SECRET}} | base64
